INSERT INTO CURRENCY (ID, SYMBOL, PRICE_USD) VALUES (90, 'BTC', 1);
INSERT INTO CURRENCY (ID, SYMBOL, PRICE_USD) VALUES (80, 'ETH', 1);
INSERT INTO CURRENCY (ID, SYMBOL, PRICE_USD) VALUES (48543, 'SOL', 1);